#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   \#3b4252
bspc config focused_border_color  \#8fbcbb
bspc config presel_feedback_color \#8fbcbb

#AutoStart application
sxhkd &
picom --config /home/aadhil/.config/picom/picom.conf &
feh --bg-scale /home/aadhil/Pictures/nordic-wallpapers/ign_unsplash40.png
dunst &
polybar &
